[project]
name = "cppposit"
version = "1.0.0"

# Optional, adding this will enable direct links from the documentation
# to your source code.
git_repo_url = "https://github.com/federicorossifr/cppposit/"
git_default_branch = "main"

[pages]
homepage="docs/getting_started.md"
paths = [
    "docs/Examples.md",
    "docs/Backends.md",
    "docs/Tabulation.md"
]

[ignore]
paths = [
    "include/floats",
    "include/interface",
    "include/traits/floattraits.hpp",
    "include/traits/fixedtraits.hpp",
    "include/typehelpers.hpp",
    "include/bithippop.hpp"

]



[paths]
compile_commands = "builddir/compile_commands.json"
output_dir = "cppposit_docs/"
