name: codecov

on:
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Build and run tests
        run: >
          mkdir build;
          cd build;
          cmake ../ ;
          make tests;
          ./test/test_coverage;
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          gcov: true
          gcov-include: posit.h
