name: codecov

on:
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Configure CMAKE
        run: cmake -B ${{github.workspace}}/buildc -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        
      - name: Build tests
        run: cmake --build ${{github.workspace}}/buildc --target tests;
        
      - name: Run tests
        run: ./buildc/tests/test_coverage
        
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          gcov: true
          gcov-include: posit.h
